apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: default
  labels:
    app: go-db  # important to service monitor to select the rights to scrape the metrics from
type: generic
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: mysecretpassword
  # Example:
  # password: {{ .Values.password | b64enc }}