apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]  # To allow jenkins to patch deployments

- apiGroups: [""]
  resources: ["pods", events"]
  verbs: ["get", "list", "watch"]

