apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: default
type: generic
data:
  DB_USERNAME: postgres
  DB_PASSWORD: mysecretpassword
  # Example:
  # password: {{ .Values.password | b64enc }}