apiVersion: v1
kind: Service
metadata:
  name: go-db-service
  namespace: default
spec:
  selector:
    app: go-db
  type: ClusterIP
  ports:
  - name: go-db-service
    protocol: TCP
    port: 8080
    targetPort: 8080 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.