apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: default
  labels:
    app: go-db  # important to service monitor to select the rights to scrape the metrics from
type: generic
stringData:
  DB_USERNAME: {{ .Values.postgresql.database.credentials.username }}
  DB_PASSWORD: {{ .Values.postgresql.database.credentials.password }}
  # Example:
  # password: {{ .Values.postgresql.database.credentials.password | b64enc }} 