apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.name }}
spec:
  accessModes: 
    - {{ .Values.postgresql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}