apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: default
type: Opaque
stringData:
  postgres_user: {{ .Values.postgresql.database.credentials.username }}
  postgres_password: {{ .Values.postgresql.database.credentials.password }}