apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-role-binding
  namespace: default
subjects:            # assigning role to service account
- kind: ServiceAccount   
  name: jenkins
  namespace: default
roleRef:             # role that's being assigned to service account
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer