# long-lived-service-account-token-secret for Jenkins to access K8s
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: jenkins    # long-lived ServiceAccountToken for Jenkins to login
type: kubernetes.io/service-account-token